name: powerpay
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  image_picker: ^1.0.7
  printing: ^5.12.0
  need_resume: ^1.0.7+1
  google_fonts: ^4.0.4
  url_launcher: ^6.2.5
  firebase_messaging: ^15.0.1
  share_plus: ^9.0.0
  share: ^2.0.0
  flutter_share: ^2.0.0
  path_provider: ^2.1.3
  firebase_core: ^3.1.0
  flutter_slidable: ^3.1.0
  device_uuid: ^0.0.4
  flutter_screenutil: ^5.9.0
  flutter_fcm: ^1.2.1
  permission_handler: ^11.3.1
  sizer: ^2.0.15
  flutter_local_notifications: ^17.1.2
  firebase_auth: ^5.1.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  intl: ^0.19.0
  get_it: ^7.2.0
  path: ^1.8.3
  gallery_saver: ^2.3.2
  gradient_floating_button: ^0.0.3
  flutter_tawk: ^0.1.0
  draggable_fab: ^0.1.4
  flutter_secure_storage: ^9.0.0
  http: ^0.13.6
  flutter_login_fix: ^4.2.0
  json_annotation: ^4.8.1
  animated_splash_screen: ^1.3.0




flutter_icons:
  image_path: "assets/icon/Powerpay_Rounded.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/duit-now.png
      - assets/duitnow-logo.jpg
      - assets/fpx-gateway-icon.png
      - assets/ic_f.png
      - assets/ic_b.png
      - assets/ic_s.png
      #official telco logos
      - assets/TelcoLogos/01_Onexox.png
      - assets/TelcoLogos/02_Hotlink.png
      - assets/TelcoLogos/03_Digi.png
      - assets/TelcoLogos/04_Celcom.png
      - assets/TelcoLogos/05_UMobile.png
      - assets/TelcoLogos/06_TuneTalk.png
      - assets/TelcoLogos/07_Redone.png
      - assets/TelcoLogos/08_Hellosim.png
      - assets/TelcoLogos/09_HaloTelco.png
      - assets/TelcoLogos/10_Beone.png
      - assets/TelcoLogos/11_Yes.png
      - assets/TelcoLogos/12_Tonewow.png
      #official logo
      - assets/Powerpay_Logo/Gradient Colour/Logo_Horizontal.png
      - assets/Powerpay_Logo/Gradient Colour/Logo_Horizontal.svg
      - assets/Powerpay_Logo/Gradient Colour/Logo_Vertical.png
      - assets/Powerpay_Logo/Gradient Colour/Logo_Vertical.svg
      - assets/Powerpay_Logo/Gradient Colour/Logo_icon.png
      - assets/Powerpay_Logo/Gradient Colour/Logo_icon.svg
      - assets/Powerpay_Logo/Gradient White Colour/Logo_Horizontal.png
      - assets/Powerpay_Logo/Gradient White Colour/Logo_Horizontal.svg
      - assets/Powerpay_Logo/Gradient White Colour/Logo_Vertical.png
      - assets/Powerpay_Logo/Gradient White Colour/Logo_Vertical.svg
      - assets/Powerpay_Logo/White Colour/Logo_Horizontal.png
      - assets/Powerpay_Logo/White Colour/Logo_Horizontal.svg
      - assets/Powerpay_Logo/White Colour/Logo_Vertical.png
      - assets/Powerpay_Logo/White Colour/Logo_Vertical.svg
      - assets/Powerpay_Logo/White Colour/Logo_icon.png
      - assets/Powerpay_Logo/White Colour/Logo_icon.svg
      - assets/icon/Powerpay_Rounded.png
      - assets/icon/Powerpay_Square.png
      # blank
      - assets/Empty.png      
      # bottom navigation bar icons
      - assets/BottomLogo/Home.png
      - assets/BottomLogo/History.png
      - assets/BottomLogo/Balance.png
      - assets/BottomLogo/Messages.png
      - assets/BottomLogo/Settings.png
      # settings page
      - assets/Settings/About.png
      - assets/Settings/ChangeName.png
      - assets/Settings/ChangePassword.png
      - assets/Settings/Commission.png
      - assets/Settings/Logout.png
      - assets/Settings/Privacy.png
      - assets/Settings/Register.png
      - assets/Settings/Settings.png
      - assets/Settings/Terms.png
      # Home page
      - assets/Home/HomePP.png
      - assets/fab.png
      # KYC page
      - assets/Kyc/KYC_Verf.png
      - assets/Kyc/KYC_Line.png
      - assets/Kyc/KYC_Camera.png
      # Register dealer page
      - assets/Settings/Registerdealer/Phone.png
      - assets/Settings/Registerdealer/Shop.png
      - assets/Settings/Registerdealer/Key.png
      - assets/Settings/Openeye.png
      - assets/Settings/Closeeye.png
      - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# fonts:
# - family: Montserrat
#   fonts:
#     - asset: assets/open-sans.ttf


# fonts:
# - family: OpenSans
#   fonts:
#     - asset: assets/fonts/OpenSans-Regular.ttf