// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkYzBUIrLBzNp1T15Wr7t3oNnbaq8hc_o',
    appId: '1:278420526152:web:68cceda6724a98b7f8747d',
    messagingSenderId: '278420526152',
    projectId: 'official-powerpay-messaging',
    authDomain: 'official-powerpay-messaging.firebaseapp.com',
    storageBucket: 'official-powerpay-messaging.appspot.com',
    measurementId: 'G-ZZX0NYJPNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuTUQ4INqbGzGaXHa1Vk3kBK6gbELECyc',
    appId: '1:278420526152:android:8f8194a03aec7ab6f8747d',
    messagingSenderId: '278420526152',
    projectId: 'official-powerpay-messaging',
    storageBucket: 'official-powerpay-messaging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-5vfV7HkNXjen4-n5J8FgZAfBIx8g5Gw',
    appId: '1:278420526152:ios:1db5ff68dc17b9daf8747d',
    messagingSenderId: '278420526152',
    projectId: 'official-powerpay-messaging',
    storageBucket: 'official-powerpay-messaging.appspot.com',
    iosBundleId: 'com.powerpay.powerpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-5vfV7HkNXjen4-n5J8FgZAfBIx8g5Gw',
    appId: '1:278420526152:ios:1db5ff68dc17b9daf8747d',
    messagingSenderId: '278420526152',
    projectId: 'official-powerpay-messaging',
    storageBucket: 'official-powerpay-messaging.appspot.com',
    iosBundleId: 'com.powerpay.powerpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkYzBUIrLBzNp1T15Wr7t3oNnbaq8hc_o',
    appId: '1:278420526152:web:d2500b6211fd779af8747d',
    messagingSenderId: '278420526152',
    projectId: 'official-powerpay-messaging',
    authDomain: 'official-powerpay-messaging.firebaseapp.com',
    storageBucket: 'official-powerpay-messaging.appspot.com',
    measurementId: 'G-YQMNTVZVLJ',
  );

}